// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TecBurguer.Models;

#nullable disable

namespace TecBurguer.Migrations
{
    [DbContext(typeof(DBTecBurguerContext))]
    [Migration("20250826215149_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TecBurguer.Models.Administrador", b =>
                {
                    b.Property<int>("IdAdministrador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAdministrador"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdAdministrador")
                        .HasName("PK__Administ__2B3E34A8112FAF2D");

                    b.ToTable("Administrador", (string)null);
                });

            modelBuilder.Entity("TecBurguer.Models.Entregador", b =>
                {
                    b.Property<int>("IdEntregador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEntregador"));

                    b.Property<decimal?>("Avaliacao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<int?>("IdPedido")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Veiculo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdEntregador")
                        .HasName("PK__Entregad__F403B4FC8497C2EE");

                    b.HasIndex("IdPedido");

                    b.ToTable("Entregador", (string)null);
                });

            modelBuilder.Entity("TecBurguer.Models.Hamburguer", b =>
                {
                    b.Property<int>("IdHamburguer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHamburguer"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(350)
                        .IsUnicode(false)
                        .HasColumnType("character varying(350)");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Preco")
                        .HasColumnType("numeric(18,0)");

                    b.HasKey("IdHamburguer")
                        .HasName("PK__Hamburgu__5BD4D479C15C344C");

                    b.ToTable("Hamburguer", (string)null);
                });

            modelBuilder.Entity("TecBurguer.Models.HamburguerIgrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdHamburguer")
                        .HasColumnType("integer");

                    b.Property<int?>("IdIngrediente")
                        .HasColumnType("integer");

                    b.Property<int?>("QuantidadeNecessario")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdHamburguer");

                    b.HasIndex("IdIngrediente");

                    b.ToTable("HamburguerIgrediente", (string)null);
                });

            modelBuilder.Entity("TecBurguer.Models.Ingrediente", b =>
                {
                    b.Property<int>("IdIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIngrediente"));

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("IdIngrediente")
                        .HasName("PK__Ingredie__3DA4DD60DD5CC092");

                    b.ToTable("Ingrediente", (string)null);
                });

            modelBuilder.Entity("TecBurguer.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPedido"));

                    b.Property<byte[]>("DataHorario")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Descricao")
                        .HasMaxLength(350)
                        .IsUnicode(false)
                        .HasColumnType("character varying(350)");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("IdHamburguer")
                        .HasColumnType("integer");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("PrecoTotal")
                        .HasColumnType("numeric(18,0)");

                    b.HasKey("IdPedido")
                        .HasName("PK__Pedido__9D335DC34C60A6BC");

                    b.HasIndex("IdHamburguer");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Pedido", (string)null);
                });

            modelBuilder.Entity("TecBurguer.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Cep")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF9793CB8078");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("TecBurguer.Models.Entregador", b =>
                {
                    b.HasOne("TecBurguer.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("Entregadors")
                        .HasForeignKey("IdPedido")
                        .HasConstraintName("FK__Entregado__IdPed__571DF1D5");

                    b.Navigation("IdPedidoNavigation");
                });

            modelBuilder.Entity("TecBurguer.Models.HamburguerIgrediente", b =>
                {
                    b.HasOne("TecBurguer.Models.Hamburguer", "IdHamburguerNavigation")
                        .WithMany("HamburguerIgredientes")
                        .HasForeignKey("IdHamburguer")
                        .HasConstraintName("FK__Hamburgue__IdHam__5070F446");

                    b.HasOne("TecBurguer.Models.Ingrediente", "IdIngredienteNavigation")
                        .WithMany("HamburguerIgredientes")
                        .HasForeignKey("IdIngrediente")
                        .HasConstraintName("FK__Hamburgue__IdIng__4F7CD00D");

                    b.Navigation("IdHamburguerNavigation");

                    b.Navigation("IdIngredienteNavigation");
                });

            modelBuilder.Entity("TecBurguer.Models.Pedido", b =>
                {
                    b.HasOne("TecBurguer.Models.Hamburguer", "IdHamburguerNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdHamburguer")
                        .HasConstraintName("FK__Pedido__IdHambur__5441852A");

                    b.HasOne("TecBurguer.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__Pedido__IdUsuari__534D60F1");

                    b.Navigation("IdHamburguerNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("TecBurguer.Models.Hamburguer", b =>
                {
                    b.Navigation("HamburguerIgredientes");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("TecBurguer.Models.Ingrediente", b =>
                {
                    b.Navigation("HamburguerIgredientes");
                });

            modelBuilder.Entity("TecBurguer.Models.Pedido", b =>
                {
                    b.Navigation("Entregadors");
                });

            modelBuilder.Entity("TecBurguer.Models.Usuario", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
